---
title: "viz_part1"
author: "Huili Zheng"
date: "10/5/2021"
output: github_document
---
```{r}

library(tidyverse)
library(ggridges)
```

Load a dataset that we will use.
```{r}

weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```


## scattterplot

tmax vs tmin

```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point()

```



you can save ggplots
```{r}
ggp_tmax_tmin = 
  weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point()

ggp_tmax_tmin
```


## Let's fancy it up

add ... color? lines? other stuff?

```{r}
  weather_df %>%
  ggplot(aes(x = tmin, y = tmax,color = name)) + 
  geom_point()
```

```{r}
  weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .3) +
  geom_smooth(aes(color = NULL), se = FALSE) +   
  facet_grid(. ~ name)        ## aes(color=null) exclude the set for all 
```

let's make one more scatterplot.
```{r}
weather_df %>%
  ggplot(aes(x = date, y = tmax, size = prcp)) + 
  geom_point(alpha = .3) +
  facet_grid(. ~ name) +
  geom_smooth(se = FALSE)
```


## use data manipulation as part of this

```{r}
weather_df %>%
  filter(name == "CentralPark_NY") %>%
  mutate(
    tmax = tmax*(9 / 5) + 32,
    tmin = tmin*(9 / 5) + 32
  ) %>%
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()

```

##stacking
```{r}

weather_df %>%
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_smooth()
```

```{r}
ggplot(weather_df, aes(x = tmax, y = tmin)) + 
  geom_hex()
```

## univariate plots

```{r}
weather_df %>%
  ggplot(aes(x = tmax, fill = name)) +
  geom_histogram() +
  facet_grid(. ~name)

```

lets try other plots.

```{r}
weather_df %>%
  ggplot(aes(x = tmax, fill = name)) +
  geom_density(alpha = .3)

```

still with 'tamx' and 'name'

```{r}
weather_df %>%
  ggplot(aes(x = name, y = tmax)) + 
  geom_boxplot()
```

some people like violin box??

```{r}
weather_df %>%
  ggplot(aes(x = name, y = tmax)) + 
  geom_violin()
```

what about ridges ...
```{r}
weather_df %>%
  ggplot(aes(x = tmax, y = name)) +
  geom_density_ridges(alpha = .8, scale = .8)
## compare more than 20 cities 
```


```{r}

```