---
title: "viz_part2"
author: "Huili Zheng"
date: "10/5/2021"
output: github_document
---
```{r}

library(tidyverse)
library(patchwork)


```

Load a dataset that we will use.
```{r}

weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```


## remember this plot ...?

```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .3)
```


## lables

```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .3) +
  labs(
    title = "temperature plot",
    x = "minimum daily temperature (C)",
    y = "maximum daily temperature(C)",
    caption = "data from noaa package; temperatures in 2017."
  )
```

## sclae
start with the same plot; x and y scales.

```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .3) +
  labs(
    title = "temperature plot",
    x = "minimum daily temperature (C)",
    y = "maximum daily temperature(C)",
    caption = "data from noaa package; temperatures in 2017."
  ) +
  scale_x_continuous(
    breaks = c(-15, 0 ,15) ,
    labels = c("-15 C","0","15C")
  ) +
  scale_y_continuous(
    position = "right"
  )
```


look at color sclales

```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .3) +
  labs(
    title = "temperature plot",
    x = "minimum daily temperature (C)",
    y = "maximum daily temperature(C)",
    caption = "data from noaa package; temperatures in 2017."
  ) +
  scale_color_hue(
    name = "Location",
    h = c(100,300) )
```




```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .3) +
  labs(
    title = "temperature plot",
    x = "minimum daily temperature (C)",
    y = "maximum daily temperature(C)",
    caption = "data from noaa package; temperatures in 2017."
  ) +
  viridis::scale_color_viridis(
    name = "Location",
    discrete = TRUE)
```


## themes

shift the legend.

```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .3) +
  labs(
    title = "temperature plot",
    x = "minimum daily temperature (C)",
    y = "maximum daily temperature(C)",
    caption = "data from noaa package; temperatures in 2017."
  ) +
  viridis::scale_color_viridis(
    name = "Location",
    discrete = TRUE) +
  theme(legend.position = "bottom")
```


changethe overall themes.

```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .3) +
  labs(
    title = "temperature plot",
    x = "minimum daily temperature (C)",
    y = "maximum daily temperature(C)",
    caption = "data from noaa package; temperatures in 2017."
  ) +
  viridis::scale_color_viridis(
    name = "Location",
    discrete = TRUE) +
  theme_minimal() +       #ggthemes::theme_excel()
  theme(legend.position = "bottom")
```

## setting options

```{r, eval = FALSE}
library(tidyverse)

knitr::opys_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.color = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_color_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## data args in `geom`

```{r}
central_park = 
  weather_df %>%
  filter(name == "CentralPark_NY")

waikiki = 
  weather_df %>%
  filter(name == "Waikiki_HA")

ggplot(data = waikiki, aes(x = date, y = tmax, color = name)) +
  geom_point() +
  geom_line(data = central_park)
```

## `patchwork`

remember faceting?

```{r}
weather_df  %>%
  ggplot(aes(x = tmin, fill = name)) +
  geom_density(alpha = .5) +
  facet_grid(. ~ name)
```


what happens when you wnat multipanel plots but can't facet ...?

```{r}

tmax_tmin_p = weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  theme(legend.position = "none")

prcp_dens_p = 
  weather_df %>%
  filter(prcp > 0) %>%
  ggplot(aes(x = prcp, fill = name)) + 
  geom_density(alpha = .5)

tmax_date_p =
  weather_df %>%
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point() +
  geom_smooth(se = FALSE) +
  theme(legend.position = "none")

(tmax_tmin_p + prcp_dens_p ) / tmax_date_p
```

